version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase
      - API_KEY=13ae79fdee588c1432fcd0a0c991a763
    depends_on:
      - postgres
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...'
        sleep 5
        npm start
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
